初版
kosei-iino/JS-kadai-4 pull request #1
Opened 2020-12-02 15:58 UTC by kosei-iino

2020-12-04 01:12 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

また、この課題の【学習できる内容】に記載があるように、Classを使用する設計にすると良いかと思いますがいかがでしょうか？

2020-12-04 01:12 UTC, kouki-iwahara commented on index.html
> +<script>
jsの記述が多いので、別ファイルで記述すると良いでしょう。

2020-12-04 01:12 UTC, kouki-iwahara commented on index.html
> +<h1 id="title"></h1>
bodyタグの子要素ですので、インデントをつけましょう。

2020-12-04 01:12 UTC, kouki-iwahara commented on index.html
> +<input type="text" id="questions" style="width:100%">
formの子要素になるのでインデントをつけましょう。

2020-12-04 01:12 UTC, kouki-iwahara commented on index.html
> +let questionData = {};
初期値ではオブジェクトを定義していますが、格納されるのは配列なので、初期値も配列の定義が良いかと思います。

2020-12-04 01:12 UTC, kouki-iwahara commented on index.html
> +    if(response.ok) {
インデントがずれています。

2020-12-04 01:12 UTC, kouki-iwahara commented on index.html
> +function homeQuestion(){
関数はアロー関数で定義するのが一般的です。

2020-12-04 01:12 UTC, kouki-iwahara commented on index.html
> +    questionData[quesNum]['incorrect_answers'].forEach(function(answer,cntAnswer){
forEachのコールバックもアロー関数にしましょう。

2020-12-04 19:46 UTC, kosei-iino commented on index.html
> +let questionData = {};
ご指摘ありがとうございます。
jsonがオブジェクトだと勘違いしてしまっていました。
修正致しました。

2020-12-05 07:50 UTC, kosei-iino commented on index.html
> +    questionData[quesNum]['incorrect_answers'].forEach(function(answer,cntAnswer){
ご指摘ありがとうございます。
修正致しました。

2020-12-05 07:50 UTC, kosei-iino commented on index.html
> +    if(response.ok) {
ご指摘ありがとうございます。
修正致しました。

2020-12-05 07:51 UTC, kosei-iino commented on index.html
> +<input type="text" id="questions" style="width:100%">
ご指摘ありがとうございます。
修正致しました。

2020-12-05 07:51 UTC, kosei-iino commented on index.html
> +<h1 id="title"></h1>
ご指摘ありがとうございます。
修正致しました。

2020-12-05 12:26 UTC, kosei-iino commented on index.html
> +<script>
ご指摘ありがとうございます。
修正致しました。

2020-12-12 12:13 UTC, myzktkyk requested changes
動作は問題ありません。
コードの書き方で1点指摘があります。

2020-12-12 12:13 UTC, myzktkyk commented on openTrivia/getQuestions.js
> +}
`async` `await` を使うとこんな感じにすっきり書けます。
```suggestion
getQuestions = async () => {

  try {
    const response = await fetch('https://opentdb.com/api.php?amount=10&type=multiple');
    const json = await response.json();
    //jsonでデータセット
    dataQuestion = json['results'];
    //インスタンス生成（取得する問題の要素番号）
    createQuestion(0);
  } catch (e) {
    console.log(e);
  }
}
```

2020-12-14 12:31 UTC, merged